version: "3.8"
services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=chat-app
      - POSTGRES_DB=chat-app
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
